### ISSUE TITLE
This css causing white theme in discord

### ISSUE THREAD

**Issue by 11kaisd11** [MrDiamondDog/noUglyIconsTheme#15]
Did not get notification, sorry
https://github.com/MrDiamondDog/noUglyIconsTheme/issues/14

My ID is 646343450534346773

**Comment by MrDiamondDog** [comment]
![image](https://github.com/user-attachments/assets/6c9bf0d5-3b5d-462d-8e34-b2dceab883aa)

I don't tolerate harassment in my repositories, so I can't let you use this.

Enjoy light mode!
