### ISSUE TITLE
Crisp icon always enabled

### ISSUE THREAD

**Issue by lynrayy** [MrDiamondDog/noUglyIconsTheme#5]
Crisp icon always on, regardless crisp enabled or not

![image](https://github.com/MrDiamondDog/noUglyIconsTheme/assets/59417884/623c8b9f-11ef-4e1f-8163-ef190e87ce43)

**Comment by lynrayy** [comment]
Also stream icon always displayed as "start stream" in the call even if stream already running

**Comment by MrDiamondDog** [comment]
i believe both of these have been fixed by now or at least they work for me
