### ISSUE TITLE
Some of the icons don't work again

### ISSUE THREAD

**Issue by EthanWinters2885** [MrDiamondDog/noUglyIconsTheme#9]
I understand that Discord was updated again (HENCE, the fact some ppl using Vencord have non functional/buggy plugins for instance), but I was just giving a heads up about this theme.

EDIT: There's also a few broken icons, like the notif icon
![image](https://github.com/MrDiamondDog/noUglyIconsTheme/assets/90074580/f9ebbea4-b214-44c6-a911-d7d11e615bb2)

Take your time, there is no rush

**Comment by MrDiamondDog** [comment]
considering all of vencord just broke im not surprised

yeah this one might take a while to fix but i'll leave this issue open until it is

**Comment by EthanWinters2885** [comment]
Alrighty, but I still just wanted to inform you

**Comment by MrDiamondDog** [comment]
should be fixed

**Comment by EthanWinters2885** [comment]
Yee, has been for a while now lel, but thanks!
